# The latest versions are available at https://quiltmc.org/en/usage/latest-versions/
[versions]
minecraft = "1.21.1"
quilt_mappings = "1.21.1+build.3"

quilt_loom = "1.8.4"
quilt_loader = "0.27.0-beta.1"

fabric_api = "0.106.0+1.21.1"
ennuis_bigger_inventories = "0.2.0-beta.3+1.21"
# Keep your friends closer and keep your rivals uh, close to each other???
emi = "1.1.16+1.21.1"
jei = "19.21.0.246"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }

fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
ennuis_bigger_inventories = { module = "maven.modrinth:ennuis_bigger_inventories", version.ref = "ennuis_bigger_inventories" }
emi = { module = "dev.emi:emi-fabric", version.ref = "emi" }
jei = { module = "mezz.jei:jei-1.21.1-fabric", version.ref = "jei" }

[bundles]

[plugins]
quilt_loom = { id = "org.quiltmc.loom", version.ref = "quilt_loom" }
